### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by NikSWE** [NikSWE/flutter_feather_icons#2]
Comment down below if you would love to maintain this project.

**Comment by II11II** [comment]
Hi @NikSWE,
I would like to support this project

**Comment by NikSWE** [comment]
hey @II11II nice to know you are interested in this project. So how do you plan to manage and keep this repo up to date with the feather icons github repo

**Comment by NikSWE** [comment]
okay adding you as contributor
